In [16]:
import pandas as pd
import numpy as np
import scipy as sp
import scipy.stats
import pandas_datareader as pdr
from datetime import date
import matplotlib.pyplot as plt
import seaborn as sns
import io
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import statsmodels.api as sm

In [17]:
mlb1 = pd.read_excel('./data/mlb1.xls')
mlb1.head()

,salary,teamsal,nl,years,games,atbats,runs,hits,doubles,triples,...,runsyr,percwhte,percblck,perchisp,blckpb,hispph,whtepw,blckph,hisppb,lsalary
0,6329213,38407380,1,12,1705,6705,1076,1939,320,67,...,89.66666,70.278,18.8442,10.8778,0,0,70.278,0,0,15.66069
1,3375000,38407380,1,8,918,3333,407,863,156,38,...,50.87500,70.278,18.8442,10.8778,18.8442,0,0,10.8778,0,15.03191
2,3100000,38407380,1,5,751,2807,370,840,148,18,...,74.00000,70.278,18.8442,10.8778,0,0,70.278,0,0,14.94691
3,2900000,38407380,1,8,1056,3337,405,816,143,18,...,50.62500,70.278,18.8442,10.8778,0,0,70.278,0,0,14.88022
4,1650000,38407380,1,12,1196,3603,437,928,19,16,...,36.41667,70.278,18.8442,10.8778,18.8442,0,0,10.8778,0,14.31629

In [18]:
mlb1.describe()

,salary,teamsal,nl,years,games,atbats,runs,hits,doubles,triples,...,pcinc,gamesyr,hrunsyr,atbatsyr,allstar,slugavg,rbisyr,sbasesyr,runsyr,lsalary
count,3.530000e+02,3.530000e+02,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,...,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000,353.000000
mean,1.345672e+06,3.079483e+07,0.475921,6.325779,648.424929,2168.592068,290.402266,584.736544,103.881020,16.733711,...,18833.138810,90.076044,7.119053,293.027990,9.242893,39.530157,35.050208,8.501081,38.582988,13.492183
std,1.407352e+06,8.722411e+06,0.500129,3.880142,538.697499,2025.059766,301.010915,575.378562,104.323511,21.533336,...,2859.221236,36.132483,6.796920,150.166734,18.579496,19.656239,22.828766,11.101780,23.862686,1.182466
min,1.090000e+05,8.854000e+06,0.000000,1.000000,7.000000,7.000000,1.000000,1.000000,0.000000,0.000000,...,14731.000000,5.500000,0.000000,7.000000,0.000000,11.111110,0.500000,0.000000,0.500000,11.599100
25%,2.536000e+05,2.455733e+07,0.000000,3.000000,230.000000,632.000000,73.000000,164.000000,26.000000,3.000000,...,17589.000000,65.000000,1.700000,173.500000,0.000000,33.968330,17.666670,1.000000,18.600000,12.443510
50%,6.750000e+05,3.413650e+07,0.000000,6.000000,520.000000,1585.000000,191.000000,419.000000,70.000000,9.000000,...,18407.000000,94.666660,5.166667,292.500000,0.000000,38.329980,31.400000,4.142857,35.333330,13.422470
75%,2.250000e+06,3.779200e+07,1.000000,9.000000,930.000000,3071.000000,407.000000,818.000000,147.000000,23.000000,...,19683.000000,117.000000,10.333330,410.285700,11.764710,43.120190,48.222220,11.473680,55.888890,14.626440
max,6.329213e+06,4.286600e+07,1.000000,20.000000,2729.000000,10554.000000,1570.000000,3025.000000,634.000000,142.000000,...,26414.000000,159.000000,31.428570,627.222200,85.714290,380.188700,97.625000,76.250000,105.142900,15.660690

In [19]:
from statsmodels.formula.api import ols

In [20]:
equation_mlb = 'lsalary~games+hruns+rbis+bavg+catcher+hispan'
results = ols(equation_mlb, mlb1).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                lsalary   R-squared:                       0.453
Model:                            OLS   Adj. R-squared:                  0.444
Method:                 Least Squares   F-statistic:                     47.84
Date:                Thu, 07 May 2020   Prob (F-statistic):           1.30e-42
Time:                        15:33:16   Log-Likelihood:                -452.92
No. Observations:                 353   AIC:                             919.8
Df Residuals:                     346   BIC:                             946.9
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     11.7314      0.342     34.277      0.000      11.058      12.405
games          0.0010      0.000      3.335      0.001       0.000       0.002
hruns          0.0023      0.002      0.952      0.342      -0.002       0.007
rbis           0.0002      0.001      0.207      0.836      -0.002       0.002
bavg           0.0036      0.001      2.758      0.006       0.001       0.006
catcher        0.0060      0.136      0.044      0.965      -0.261       0.273
hispan        -0.0915      0.124     -0.740      0.460      -0.335       0.152
==============================================================================
Omnibus:                        2.268   Durbin-Watson:                   1.309
Prob(Omnibus):                  0.322   Jarque-Bera (JB):                2.010
Skew:                          -0.170   Prob(JB):                        0.366
Kurtosis:                       3.145   Cond. No.                     6.94e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.94e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [21]:
equation_mlb_r = 'lsalary~games+bavg+catcher+hispan'
results_r = ols(equation_mlb_r, mlb1).fit()
results_r.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                lsalary   R-squared:                       0.442
Model:                            OLS   Adj. R-squared:                  0.435
Method:                 Least Squares   F-statistic:                     68.86
Date:                Thu, 07 May 2020   Prob (F-statistic):           6.76e-43
Time:                        15:33:17   Log-Likelihood:                -456.63
No. Observations:                 353   AIC:                             923.3
Df Residuals:                     348   BIC:                             942.6
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     11.6975      0.331     35.350      0.000      11.047      12.348
games          0.0014   9.29e-05     14.596      0.000       0.001       0.002
bavg           0.0036      0.001      2.817      0.005       0.001       0.006
catcher       -0.0136      0.137     -0.100      0.920      -0.282       0.255
hispan        -0.1202      0.124     -0.970      0.333      -0.364       0.124
==============================================================================
Omnibus:                        0.487   Durbin-Watson:                   1.317
Prob(Omnibus):                  0.784   Jarque-Bera (JB):                0.609
Skew:                          -0.062   Prob(JB):                        0.737
Kurtosis:                       2.839   Cond. No.                     6.10e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.1e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [22]:
hyp = 'hruns=0, rbis=0, catcher=0, hispan=0'
test = results.f_test(hyp)
print(test)

<F test: F=array([[2.07652562]]), p=0.08345302765160059, df_denom=346, df_num=4>